Added support backing up and restoring of saved values.
endorama/2ami pull request #34
Opened 2021-10-30 22:52 UTC by backwards-rat-race

Saved backups are AES encrypted, each key encrypted individually for easier (de)serialisation. New commands are restore <file-path> and backup <file-path> with a password then prompted for both commands.

Been running 2ami on my work laptop and needed to migrate the keys, noticed you had a couple issues open for restore and backup ( #14 and #13). Hope the changes are of some use.

2021-11-03 22:28 UTC, endorama commented
WOW! Thank you :D I did not expect this to be used by someone else other than me, so highly appreciated. (Plus code is a mess so thank you for your effort!)

Approving CI and going to review it.

2021-11-03 23:52 UTC, endorama requested changes
As I cannot push on your branch, you need to remove the `backupKey` function, as is failing the lint step: https://deepsource.io/gh/endorama/2ami/run/8fbbad6c-74fc-407c-a578-9acadf358168/go/SCC-U1000

Apart from that, this looks ok (I'll work on adding tests in a future PR)

2021-11-04 19:02 UTC, backwards-rat-race commented
The gnome keyring support is what brought me to it, and it works great - so thank you for that. I've removed that function now, had a quick scan through and don't spot anything else - let me know if there is. Thanks

2021-11-04 21:17 UTC, endorama commented
> gnome keyring support is what brought me to it, and it works great

BTW I just added support for using different collection (so is possible to use a different one than `login` that automatically unlocks at login).

2021-11-04 21:18 UTC, endorama approved these changes

2021-11-04 21:18 UTC, endorama commented
CI is green so I'll merge it.

Thank you for the contribution!

2021-11-04 21:18 UTC, merged

2021-11-04 23:51 UTC, endorama commented
I made pre-release, [`v0.6.0-rc.11`](https://github.com/endorama/2ami/releases/tag/untagged-c06e1dc1cc51a49bfb2c) to use the new backup/restore features! (I'm still ironing the release process but the binary is there)